### ISSUE TITLE
这个插件好像没用了，装了按Alt+T没反应，用的Webstorm 2020.3

### ISSUE THREAD

**Issue by liaokaime** [RmondJone/JsonToTypeScript#1]

**Comment by RmondJone** [comment]
好，我等会看看，你先看下是不是输入法冲突

**Comment by liaokaime** [comment]
不是其它软件的热键冲突，Alt+T 被 Webstorm占用了，动作是展开Menu>Tools

**Comment by RmondJone** [comment]
那你可以先把WebStrom的给先改掉换成其他的或者删除，后续我把这个加一个快捷菜单或者自定义快捷键，防止Alt+T被其他热键占用的这种情况。

**Comment by liaokaime** [comment]
我把JsonToTypeScript快捷键改成了别的，依然不起作用。你的插件似乎是2016年写的，也许Webstorm其中变化了什么。

**Comment by RmondJone** [comment]
你用的哪个版本？我记得我近期提交过一个版本

**Comment by liaokaime** [comment]
Webstorm 2020.3

**Comment by liaokaime** [comment]
JsonToTypeScript是最新版本

**Comment by RmondJone** [comment]
好，我明天看看好不好改

**Comment by liaokaime** [comment]
好的

**Comment by RmondJone** [comment]
> 好的

我这边刚刚试了下2020.3版本的Webstorm好像没有你说的问题，快捷键搜索了一下也没有找到冲突

**Comment by RmondJone** [comment]
![image](https://user-images.githubusercontent.com/10555850/113386123-20e5d500-93bc-11eb-81c3-1f6ef853cde9.png)

**Comment by RmondJone** [comment]
> 我把JsonToTypeScript快捷键改成了别的，依然不起作用。你的插件似乎是2016年写的，也许Webstorm其中变化了什么。

确认下你的版本是否是对的，我这边的版本是1.3.0，是我2020年写的。

![image](https://user-images.githubusercontent.com/10555850/113386343-a36e9480-93bc-11eb-9f1f-d6f66b054565.png)

**Comment by liaokaime** [comment]
版本是1.3.0，系统是windows，已经装了的插件是这些
![image](https://user-images.githubusercontent.com/27792976/113388019-ff86e800-93bf-11eb-8c69-3c2cca167472.png)

**Comment by liaokaime** [comment]
不好重现就不弄了吧

**Comment by RmondJone** [comment]
> 不好重现就不弄了吧

我切到Window试下

**Comment by RmondJone** [comment]
> 版本是1.3.0，系统是windows，已经装了的插件是这些
> ![image](https://user-images.githubusercontent.com/27792976/113388019-ff86e800-93bf-11eb-8c69-3c2cca167472.png)

Window的我也试了，好像也没有问题，等后续其他人反馈吧。
![image](https://user-images.githubusercontent.com/10555850/113391670-77581100-93c6-11eb-9752-571adbb7a3d6.png)

**Comment by liaokaime** [comment]
行
