### ISSUE TITLE
类名识别错误

### ISSUE THREAD

**Issue by StringKe** [RmondJone/JsonToTypeScript#3]
![image](https://user-images.githubusercontent.com/31089228/124413783-ef4a2480-dd83-11eb-8d9c-c21c6010eca8.png)

另外能否直接生成 interface 定义。

**Comment by RmondJone** [comment]
类名是根据文件名生成的，文件名是啥类名就是啥，这个你自己手动改下就行，我们目前Ts开发文件名都是以驼峰的形式命名，所以没这个问题。插件默认生成的是Class，个人认为Class表示实体更合理一些，因为可以定义方法，你也可以手动改下。
